name: app_store_connect_api_v1
description: App Store Connect Api
version: 0.0.6
homepage: https://github.com/iptodays/app_store_connect_api

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/convert
  convert: ^3.1.1
  # https://pub.dev/packages/dart_jsonwebtoken
  dart_jsonwebtoken: ^2.12.0
  # https://pub.dev/packages/dio
  dio: ^5.3.3
  # https://pub.dev/packages/crypto
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter: